# Generated by Django 5.0.1 on 2025-01-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_gender_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
