# Generated by Django 5.0.1 on 2024-12-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
