# Generated by Django 5.0.1 on 2025-01-02 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='active',
            field=models.ManyToManyField(blank=True, related_name='active', to=settings.AUTH_USER_MODEL),
        ),
    ]
