# Generated by Django 5.0.1 on 2025-01-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_alter_workspace_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
