# Generated by Django 5.0.1 on 2025-01-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_project_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='leader',
        ),
    ]
