# Generated by Django 5.0.1 on 2025-01-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_remove_project_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
