from django.urls import path
from . import views

urlpatterns = [
    path('list/user/workspace', views.UserWorkSpace.as_view()),
    path('search/result', views.SearchResult.as_view()),
    path('switch/workspace', views.SwitchWorkspace.as_view()),
    path('create/workspace', views.CreateWorkSpace.as_view()),
    path('create/task', views.CreateTaskView.as_view()),
    path('list/task', views.ListTaskView.as_view()),
    path('task/due/today', views.TodaysDueTaskView.as_view()),
    path('task/status', views.StatusOfTasks.as_view()),
    path('search/task/members', views.SearchTaskMembers.as_view()),
    path('update/task/<int:pk>', views.UpdateTask.as_view()),
    path('update/project/<int:pk>', views.UpdateProject.as_view()),
    path('team/memebers', views.TeamMembers.as_view()),
    path('leave/team/<int:pk>', views.LeaveTeam.as_view()),
    path('list/project', views.ListProjectView.as_view()),
    path('create/project', views.CreateProjectView.as_view()),
    path('project/<int:pk>', views.DetailProjectView.as_view()),
    path('add/project/favourite/<int:pk>', views.AddProjectToFavorites.as_view()),
    path('project/task/due/<int:pk>', views.ProjectTaskDueToday.as_view()),
    path('add/member/project/<int:pk>', views.AddUserToProject.as_view()),
    path('remove/member/project/<int:pk>', views.RemoveUserFromProject.as_view()),
    path('delete/project/<int:pk>', views.DeleteProject.as_view()),
    path('delete/task/<int:pk>', views.DeleteTask.as_view()),
    path('complete/task/<int:pk>', views.CompleteTaskView.as_view()),
    path('response/invitation/<int:pk>', views.ResponseToInvitationView.as_view()),
    path('send/invitation', views.SendInvitationView.as_view()),
    path('user/invitations', views.UserInvitationView.as_view()),
    path('user/notifications', views.NotificationView.as_view()),
    path('user/unread/notifications', views.UnReadNotificationView.as_view()),
    path('markasread/notifications/<int:pk>', views.MarkAsReadView.as_view()),
    path('markallasread/notifications', views.MarkAllAsReadView.as_view()),
]